# Generated by Django 4.2.11 on 2024-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
