# Generated by Django 4.2.11 on 2024-04-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shape24_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedProjects",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="shape24_app.users",
                    ),
                ),
            ],
            options={
                "db_table": "assigned_projects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("project_id", models.IntegerField(primary_key=True, serialize=False)),
                ("project_title", models.CharField(max_length=500)),
                ("availability", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects",
                "managed": False,
            },
        ),
    ]
