# Generated by Django 2.1.15 on 2024-04-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shape24_app', '0002_assignedprojects_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedprojects',
            options={'managed': True},
        ),
    ]
