# Generated by Django 2.1.15 on 2024-04-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shape24_app', '0003_auto_20240409_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedprojects',
            options={'managed': False},
        ),
    ]
